import test from 'node:test';
import assert from 'node:assert/strict';
import {SyncEngine,clone,notionContext} from '../schedule-sync-core.mjs';
const state=title=>({version:5,workConfig:{label:'회사',start:'09:00',end:'18:00',weekdays:[1]},workExceptions:{},workOverrides:{},categories:[],trackerDefs:[],trackerLogs:{},sleepLogs:{},events:[{id:'1',title,startDate:'2026-09-21',recurrence:{type:'none'},exdates:[]}]});
function memory(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),m}}
function server(initial){let revision=1;return {row:initial?{state:clone(initial),updated_at:'1'}:null,writes:0,offline:false,async read(){if(this.offline)throw Error('offline');return clone(this.row)},async insert(s){if(this.row)return null;this.writes++;return clone(this.row={state:clone(s),updated_at:String(++revision)})},async update(s,stamp){if(this.offline)throw Error('offline');if(this.row?.updated_at!==stamp)return null;this.writes++;return clone(this.row={state:clone(s),updated_at:String(++revision)})}}}
function device(api,s,{notion=false,existing=true,storage=memory()}={}){let local=clone(s),busy=false;const statuses=[];const bridge={read:()=>clone(local),apply:v=>local=clone(v),originalCache:existing?JSON.stringify(s):null,busy:()=>busy};const e=new SyncEngine({api,bridge,notion,scope:'project|user',storage,status:(...args)=>statuses.push(args)});return {e,storage,statuses,read:()=>local,set:v=>local=clone(v),edit(v){local=clone(v);e.localChanged();clearTimeout(e.timer)},busy:v=>busy=v}}
test('Notion seeds only existing state and keeps a pre-migration backup',async()=>{const api=server(),d=device(api,state('notion'),{notion:true});await d.e.reconcile();assert.equal(api.row.state.events[0].title,'notion');assert.equal(api.writes,1);assert([...d.storage.m.keys()].some(k=>k.startsWith('myWeekSyncBackup:')));await d.e.reconcile();assert.equal(api.writes,1)});
test('direct PC cannot seed even after edits and retries',async()=>{const api=server(),d=device(api,state('old'));await d.e.reconcile();d.edit(state('edited old'));await d.e.reconcile();await d.e.reconcile();assert.equal(api.row,null);assert.equal(d.e.dirty,true)});
test('fresh Notion iframe cannot upload demonstration defaults',async()=>{const api=server(),d=device(api,state('sample'),{notion:true,existing:false});await d.e.reconcile();assert.equal(api.writes,0)});
test('unrelated iframe / malicious referrer cannot seed',()=>{assert(!notionContext(true,'https://notion.so.evil.test/'));assert(!notionContext(false,'https://notion.so/'));assert(!notionContext(true,''));assert(notionContext(true,'https://app.notion.com/p/123'));assert(notionContext(true,'',['https://www.notion.so']))});
test('new PC pulls remote, backs up cache, never writes remote',async()=>{const api=server(state('cloud')),d=device(api,state('old'));await d.e.reconcile();assert.equal(d.read().events[0].title,'cloud');assert.equal(api.writes,0)});
test('two devices converge and self echo produces no write loop',async()=>{const api=server(state('base')),a=device(api,state('base')),b=device(api,state('base'));await a.e.reconcile();await b.e.reconcile();a.edit(state('new'));await a.e.reconcile();await b.e.reconcile();await a.e.reconcile();assert.equal(b.read().events[0].title,'new');assert.equal(api.writes,1)});
test('offline edits survive reload and upload on reconnect when baseline unchanged',async()=>{const api=server(state('base')),a=device(api,state('base'));await a.e.reconcile();api.offline=true;a.edit(state('offline'));await a.e.reconcile();assert.equal(a.read().events[0].title,'offline');a.e.stop();const b=device(api,a.read(),{storage:a.storage});api.offline=false;await b.e.reconcile();assert.equal(api.row.state.events[0].title,'offline');assert(!b.e.dirty)});
test('offline edit does not silently overwrite newer server state',async()=>{const api=server(state('base')),a=device(api,state('base'));await a.e.reconcile();a.edit(state('local'));await api.update(state('other'),'1');await a.e.reconcile();assert(a.e.conflict);assert.equal(api.row.state.events[0].title,'other');assert.equal(a.read().events[0].title,'local')});
test('conditional write protects race between fetch and save',async()=>{const api=server(state('base')),d=device(api,state('base'));await d.e.reconcile();d.edit(state('ours'));api.update=async function(){this.row={state:state('theirs'),updated_at:'99'};return null};await d.e.reconcile();assert(d.e.conflict);assert.equal(api.row.state.events[0].title,'theirs')});
test('initial insert race never overwrites winning migration',async()=>{const api=server(),d=device(api,state('ours'),{notion:true});api.insert=async function(){this.row={state:state('winner'),updated_at:'99'};return null};await d.e.reconcile();assert(d.e.conflict);assert.equal(api.row.state.events[0].title,'winner')});
test('remote data waits for open editor, then renders without reload',async()=>{const api=server(state('cloud')),d=device(api,state('old'));d.busy(true);await d.e.reconcile();assert.equal(d.read().events[0].title,'old');d.busy(false);await d.e.reconcile();assert.equal(d.read().events[0].title,'cloud')});
test('invalid remote state or full backup storage cannot replace local state',async()=>{const api=server(state('cloud')),d=device(api,state('local'));api.row.state={};await d.e.reconcile();assert.equal(d.read().events[0].title,'local');api.row.state=state('cloud');d.storage.setItem=()=>{throw Error('quota')};await d.e.reconcile();assert.equal(d.read().events[0].title,'local')});
test('logout ignores late network response',async()=>{const api=server(state('cloud')),d=device(api,state('local'));let resolve;api.read=()=>new Promise(r=>resolve=r);const p=d.e.reconcile();await Promise.resolve();d.e.stop();resolve(api.row);await p;assert.equal(d.read().events[0].title,'local')});
test('manual upload and pull preserve both sides in backups',async()=>{const api=server(state('cloud')),d=device(api,state('local'));await d.e.upload();assert.equal(api.row.state.events[0].title,'local');await api.update(state('new cloud'),api.row.updated_at);await d.e.pull();assert.equal(d.read().events[0].title,'new cloud');assert(d.storage.m.size>=3)});
test('pending data belonging to same user is not silently cleared by another cache',async()=>{const api=server(state('base')),a=device(api,state('base'));await a.e.reconcile();a.edit(state('pending'));const b=device(api,state('different cache'),{storage:a.storage});await b.e.reconcile();assert(b.e.conflict);assert.equal(api.writes,0)});
test('original Notion cache is seeded without losing fields normalized by old app startup',async()=>{const api=server(),d=device(api,state('original'),{notion:true});d.set(state('normalized'));await d.e.reconcile();assert.equal(api.row.state.events[0].title,'original')});
test('edits during a pending server write are not lost',async()=>{const api=server(state('base')),d=device(api,state('base'));await d.e.reconcile();d.edit(state('first'));const update=api.update.bind(api);let resume,started;const wait=new Promise(r=>started=r);api.update=async(s,stamp)=>{started();await new Promise(r=>resume=r);return update(s,stamp)};const p=d.e.reconcile();await wait;d.edit(state('second'));api.update=update;resume();await p;await d.e.chain;assert.equal(api.row.state.events[0].title,'second')});
test('missing server after previous sync does not silently recreate deleted data',async()=>{const api=server(state('base')),d=device(api,state('base'),{notion:true});await d.e.reconcile();api.row=null;await d.e.reconcile();assert.equal(api.writes,0)});
